Traceback (most recent call last):
  File "/home/masarom/.local/bin/uvicorn", line 8, in <module>
    sys.exit(main())
  File "/home/masarom/.local/lib/python3.6/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/home/masarom/.local/lib/python3.6/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/home/masarom/.local/lib/python3.6/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/masarom/.local/lib/python3.6/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/home/masarom/.local/lib/python3.6/site-packages/uvicorn/main.py", line 426, in main
    run(app, **kwargs)
  File "/home/masarom/.local/lib/python3.6/site-packages/uvicorn/main.py", line 452, in run
    server.run()
  File "/home/masarom/.local/lib/python3.6/site-packages/uvicorn/server.py", line 69, in run
    return asyncio.get_event_loop().run_until_complete(self.serve(sockets=sockets))
  File "/usr/lib64/python3.6/asyncio/base_events.py", line 484, in run_until_complete
    return future.result()
  File "/home/masarom/.local/lib/python3.6/site-packages/uvicorn/server.py", line 76, in serve
    config.load()
  File "/home/masarom/.local/lib/python3.6/site-packages/uvicorn/config.py", line 456, in load
    self.loaded_app = import_from_string(self.app)
  File "/home/masarom/.local/lib/python3.6/site-packages/uvicorn/importer.py", line 24, in import_from_string
    raise exc from None
  File "/home/masarom/.local/lib/python3.6/site-packages/uvicorn/importer.py", line 21, in import_from_string
    module = importlib.import_module(module_str)
  File "/usr/lib64/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "./main.py", line 14, in <module>
    from processor import ResumeProcessor
  File "./processor.py", line 3, in <module>
    from llm_service import call_gpt
  File "./llm_service.py", line 2, in <module>
    from config import OPENAI_API_KEY
  File "./config.py", line 3, in <module>
    from dotenv import load_dotenv
ModuleNotFoundError: No module named 'dotenv'
Traceback (most recent call last):
  File "/home/masarom/.local/bin/uvicorn", line 8, in <module>
    sys.exit(main())
  File "/home/masarom/.local/lib/python3.6/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/home/masarom/.local/lib/python3.6/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/home/masarom/.local/lib/python3.6/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/masarom/.local/lib/python3.6/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/home/masarom/.local/lib/python3.6/site-packages/uvicorn/main.py", line 426, in main
    run(app, **kwargs)
  File "/home/masarom/.local/lib/python3.6/site-packages/uvicorn/main.py", line 452, in run
    server.run()
  File "/home/masarom/.local/lib/python3.6/site-packages/uvicorn/server.py", line 69, in run
    return asyncio.get_event_loop().run_until_complete(self.serve(sockets=sockets))
  File "/usr/lib64/python3.6/asyncio/base_events.py", line 484, in run_until_complete
    return future.result()
  File "/home/masarom/.local/lib/python3.6/site-packages/uvicorn/server.py", line 76, in serve
    config.load()
  File "/home/masarom/.local/lib/python3.6/site-packages/uvicorn/config.py", line 456, in load
    self.loaded_app = import_from_string(self.app)
  File "/home/masarom/.local/lib/python3.6/site-packages/uvicorn/importer.py", line 24, in import_from_string
    raise exc from None
  File "/home/masarom/.local/lib/python3.6/site-packages/uvicorn/importer.py", line 21, in import_from_string
    module = importlib.import_module(module_str)
  File "/usr/lib64/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "./main.py", line 14, in <module>
    from processor import ResumeProcessor
  File "./processor.py", line 3, in <module>
    from llm_service import call_gpt
  File "./llm_service.py", line 2, in <module>
    from config import OPENAI_API_KEY
  File "./config.py", line 3, in <module>
    from dotenv import load_dotenv
ModuleNotFoundError: No module named 'dotenv'
